spring:
  profiles:
    include: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    add-properties: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl
  jwt:
    secret: test